# Generated by Django 4.2.1 on 2023-05-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contacto', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
